#!/usr/bin/with-contenv bash

CERTDIR=/data/cert
CONFIG=/data/derper/derper.key

if [ "$DERP_CERTMODE" = "acme.sh" ]; then
    DERP_CERTMODE=manual
fi

if [ $DERP_ENABLE_HTTP != "true" ]; then
    DERP_PORT_HTTP=-1
fi

s6-setuidgid abc \
    derper \
        --a=:$DERP_PORT_HTTPS \
        --c=$CONFIG \
        --certdir=$CERTDIR \
        --certmode=$DERP_CERTMODE \
        --hostname=$DERP_HOSTNAME \
        --http-port=$DERP_PORT_HTTP \
        --stun=$DERP_ENABLE_STUN \
        --stun-port=$DERP_PORT_STUN \
        --verify-clients=$DERP_VERIFY_CLIENTS
